name: movedb-core-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - opensim-org::opensim>=4.0.0
  - numpy>=1.20.0
  - polars>=0.20.0
  - pydantic>=2.0.0
  - loguru>=0.6.0
  - ezc3d>=1.5.0
  - pytest>=6.0
  - pytest-cov
  - black
  - flake8
  - mypy
  - pre-commit
  - conda-build
  - conda-verify
  - hatchling
  - pip
  - jupyter
  - matplotlib
  - seaborn
  - pyyaml  # For local GitHub Actions workflow validation
