name: movedb-opensim
channels:
  - opensim-org
  - conda-forge
  - defaults
dependencies:
  - python=3.12  # Latest version supported by OpenSim
  - opensim>=4.0.0
  - numpy>=1.20.0
  - polars>=0.20.0
  - pydantic>=2.0.0
  - loguru>=0.6.0
  - ezc3d>=1.5.0
  - pip
  # Note: Install movedb-core after creating environment with:
  # conda activate movedb-opensim
  # pip install movedb-core
